### ISSUE TITLE
: TypeError: <lambda>() got an unexpected keyword argument 'fan_exclusive_play'

### ISSUE THREAD

**Issue by stpf99** [universalappfactory/mopidy-hearthis#3]
hi , 
 now it is not possible to use this mopidy extension because some api changes at website happened  few days ago , hearthis.at have now added function for exclusive content for "fan subscribers"  

`is 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:     return loop.run_until_complete(main)
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:     return future.result()
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:   File "/usr/lib/python3.9/site-packages/mopidy_hearthis/hearthis_search.py", line 119, in _get_feed_async
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:     return await hearthis.get_feeds(
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:   File "/usr/lib/python3.9/site-packages/pyhearthis/hearthis.py", line 182, in get_feeds
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:     return list(map(HearThis._json_to_track, cast_list(json_data)))
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:   File "/usr/lib/python3.9/site-packages/pyhearthis/hearthis.py", line 141, in _json_to_track
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]:     return SingleTrack(**json_dict, user=User(**user_dict))
lis 22 13:47:23 ts-hpt620quadcoretc mopidy[9450]: TypeError: <lambda>() got an unexpected keyword argument 'fan_exclusive_play'`

**Comment by universalappfactory** [comment]
Hi, thank's for the info. I'll fix that.

**Comment by universalappfactory** [comment]
Ok, should be fixed.

**Comment by stpf99** [comment]
works!
